config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'trains/new'
  # get 'trains/create'
  # get 'trains/show'
  # get 'trains/edit'
  # get 'trains/update'
  # get 'trains/destroy'

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "homes#index"

  resources :homes

  resources :payments
  # get '/search', to: 'trains#search'

  resources :trains do
    # resources :tickets, only: [:show, :create, :destroy]
    collection do
      get 'search'
      get 'search_result'
    end
  end
  resources :tickets

  resources :passengers

  devise_for :users do
    resources :tickets
  end

end

app/models/train.rb
class Train < ApplicationRecord
  has_many :stops, dependent: :destroy
  has_many :stations, through: :stops
  has_many :tickets, dependent: :destroy
  has_many :journey_classes, dependent: :destroy
  has_many :daily_availabilities, dependent: :destroy
  # has_many :days, dependent: :destroy
  has_and_belongs_to_many :days

  validates :train_name, presence: true
  validates :train_number, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :source_station, presence: true
  validates :destination_station, presence: true
  validates :capacity, presence: true



  def self.search_train(source_station, destination_station, date)
    if source_station.present? && destination_station.present? && date.present?
      source_stops = Stop.where(station_id: source_station.id)
      destination_stop = Stop.where(station_id: destination_station.id)
      trains_from_source_to_destination = []
      source_stops.each do |source_stop|
        stops_after_source = Stop.where(train_id: source_stop.train_id).where('position > ?', source_stop.position)
        destination_stop = stops_after_source.find_by(station_id: destination_station.id)
        if destination_stop
          trains_from_source_to_destination << source_stop.train_id
        end
      end
      @day_name = date&.to_date&.strftime('%A')&.downcase
      @day = Day.find_by(name: @day_name)
      trains_acc_to_day = @day&.trains.where(id: trains_from_source_to_destination).pluck(:id)
      @trains = Train.where(id: trains_acc_to_day)
    else
      @trains = Train.none
    end
  end

  def self.ransackable_associations(auth_object = nil)
    ["days", "journey_classes", "stations", "stops", "tickets", "daily_availabilities"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["capacity", "created_at", "destination_station", "end_time", "id", "id_value", "source_station", "start_time", "train_name", "train_number", "updated_at"]
  end

end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController

  def search
    from_station = params[:source_station]
    to_station = params[:destination_station]
    @source_station = Station.find_by_name(from_station)
    @destination_station = Station.find_by_name(to_station)
    @date = params[:date]

    @source_error = nil
    @destination_error = nil
    @date_error = nil

    if !@source_station.present?
      @source_error = "Please provide a source station."
    end

    if !@destination_station.present?
      @destination_error = "Please provide a destination station."
    end

    if !@date.present?
      @date_error = "Date cannot be empty."
    elsif @date.to_date < Date.today
      @date_error = "Date cannot be in the past."
    end

    if @source_error || @destination_error || @date_error
      render :search
    else
      @trains = Train.search_train(@source_station, @destination_station, @date)
      @trains.each do |train|
        stops = Stop.where(train_id: train.id, station_id: @source_station.id)
        stops.each do |stop|
          new_departure_time = DateTime.parse(@date) + stop.departure_time.hour.hours + stop.departure_time.min.minutes
          stop.update!(departure_time: new_departure_time)
        end
      end
      render 'search_result'
    end
  end

  def search_result
    @train_id = params[:train_id]
    @source = params[:source]
    @destination = params[:destination]
    redirect_to new_ticket_path(train_id: @train_id, source: @source, destination: @destination)
  end

  def index
    render :search
  end

  def new
    @train = Train.new
  end

  def create
    # @train = Train.new
    # if @train.save
    #   redirect_to @train
    # else
    #   render :new
    # end
  end

  def show
    # @train = Train.find(params[:id])
  end

  def edit
    # @train = Train.find(params[:id])
  end

  def update
    # @train = Train.find(params[:id])
    # if @train.update
    #   redirect_to @train
    # else
    #   render :edit
    # end
  end

  def destroy
    # @train = Train.find(params[:id])
    # @train.destroy
    # redirect_to root_path
  end

end

app/helpers/trains_helper.rb
module TrainsHelper
  def chart_prepared?(s_time)
    s_time.in_time_zone('Asia/Kolkata') < (Time.now + 12.hours).in_time_zone('Asia/Kolkata')
  end

  def train_departured?(s_time)
    s_time.in_time_zone('Asia/Kolkata') < Time.now.in_time_zone('Asia/Kolkata')
  end
end

app/views/trains/create.html.erb
<h1>Trains#create</h1>
<p>Find me in app/views/trains/create.html.erb</p>

app/views/trains/destroy.html.erb
<h1>Trains#destroy</h1>
<p>Find me in app/views/trains/destroy.html.erb</p>

app/views/trains/edit.html.erb
<h1>Trains#edit</h1>
<p>Find me in app/views/trains/edit.html.erb</p>

app/views/trains/new.html.erb
<h1>Trains#new</h1>
<p>Find me in app/views/trains/new.html.erb</p>

app/views/trains/search.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Search Trains</title>
  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body {
      background-color: #f0f4f8; 
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .heading {
      text-align: center;
      font-weight: bold;
      color: #007bff; 
      margin-bottom: 20px;
    }
    .container {
      max-width: 600px; 
      background-color: #ffffff;
      border: 2px solid #007bff;
      border-radius: 10px;
      margin: 20px auto;
      padding: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); 
    }
    .form-label {
      font-weight: bold; 
    }
    .btn-primary {
      background-color: #007bff; 
      border-color: #007bff;
      border-radius: 5px; 
    }
    .btn-primary:hover {
      background-color: #0056b3; 
      border-color: #004085;
    }

    .error_message {
      color: #dc3545;
      font-size: 18px;
      font-weight: bold;
      text-align: center;
    }
  </style>
</head>
<body>
  <% unless user_signed_in? %>
    <% redirect_to new_user_session_path %>
  <% end %>

  <h1 class="heading">Search Train Here</h1>

  <div class="container">

    <div class="error_message" style="display: none;"></div>

    <%= form_with url: search_trains_path, method: :get do |form| %>
      <h2 class="heading">Search Train</h2>
      <div class="row mb-3">
        <div class="col-md-4">
          <%= form.label :source_station, "Source Station", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= form.text_field :source_station, id: "source", class: "form-control", onkeyup: "filterFunction('source')"%>
          <% if @source_error.present? %>
            <div class="error_message" id="source-error"><%= @source_error %></div>
          <%end%>
        </div>
        <div class="filtered-links" id="filteredsourcestation" style="display: none;">
            <div class="dropdown-item" onclick="selectStation('source', 'agra')">agra</div>
            <div class="dropdown-item" onclick="selectStation('source', 'ambala')">ambala</div>
            <div class="dropdown-item" onclick="selectStation('source', 'bhopal')">bhopal</div>
            <div class="dropdown-item" onclick="selectStation('source', 'biaora')">biaora</div>
            <div class="dropdown-item" onclick="selectStation('source', 'bina')">bina</div>
            <div class="dropdown-item" onclick="selectStation('source', 'dewas')">dewas</div>
            <div class="dropdown-item" onclick="selectStation('source', 'gwalior')">gwalior</div>
            <div class="dropdown-item" onclick="selectStation('source', 'indore')">indore</div>
            <div class="dropdown-item" onclick="selectStation('source', 'jammu tawi')">jammu tawi</div>
            <div class="dropdown-item" onclick="selectStation('source', 'jhasi')">jhasi</div>
            <div class="dropdown-item" onclick="selectStation('source', 'kathua')">kathua</div>
            <div class="dropdown-item" onclick="selectStation('source', 'katra')">katra</div>
            <div class="dropdown-item" onclick="selectStation('source', 'kota')">kota</div>
            <div class="dropdown-item" onclick="selectStation('source', 'lalitpur')">lalitpur</div>
            <div class="dropdown-item" onclick="selectStation('source', 'ludhiana')">ludhiana</div>
            <div class="dropdown-item" onclick="selectStation('source', 'maksi')">maksi</div>
            <div class="dropdown-item" onclick="selectStation('source', 'mathura')">mathura</div>
            <div class="dropdown-item" onclick="selectStation('source', 'morena')">morena</div>
            <div class="dropdown-item" onclick="selectStation('source', 'new delhi')">new delhi</div>
            <div class="dropdown-item" onclick="selectStation('source', 'palwal')">palwal</div>
            <div class="dropdown-item" onclick="selectStation('source', 'panipat')">panipat</div>
            <div class="dropdown-item" onclick="selectStation('source', 'pathankot')">pathankot</div>
            <div class="dropdown-item" onclick="selectStation('source', 'ruthiyai')">ruthiyai</div>
            <div class="dropdown-item" onclick="selectStation('source', 'sehore')">sehore</div>
            <div class="dropdown-item" onclick="selectStation('source', 'ujjain')">ujjain</div>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-4">
          <%= form.label :destination_station, "Destination Station", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= form.text_field :destination_station, id: "destination", class: "form-control", onkeyup: "filterFunction('destination')" %>
          <% if @destination_error.present? %>
            <div class="error_message" id="destination-error"><%= @destination_error %></div>
            <%end%>
        </div>
         <div class="filtered-links" id="filtereddestinationstation" style="display: none;">
            <div class="dropdown-item" onclick="selectStation('destination', 'agra')">agra</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'ambala')">ambala</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'bhopal')">bhopal</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'biaora')">biaora</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'bina')">bina</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'dewas')">dewas</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'gwalior')">gwalior</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'indore')">indore</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'jammu tawi')">jammu tawi</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'jhasi')">jhasi</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'kathua')">kathua</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'katra')">katra</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'kota')">kota</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'lalitpur')">lalitpur</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'ludhiana')">ludhiana</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'maksi')">maksi</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'mathura')">mathura</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'morena')">morena</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'new delhi')">new delhi</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'palwal')">palwal</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'panipat')">panipat</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'pathankot')">pathankot</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'ruthiyai')">ruthiyai</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'sehore')">sehore</div>
            <div class="dropdown-item" onclick="selectStation('destination', 'ujjain')">ujjain</div>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-4">
          <%= form.label :date, "Date", class: "form-label" %>
        </div>
        <div class="col-md-8">
          <%= form.date_field :date, class: "form-control", id: "date" %>
          <% if @date_error.present? %>
            <div class="error_message" id="date-error"><%= @date_error %></div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col text-center">
          <%= form.submit "Search", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>


  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
</body>
<script>
  function selectStation(inputType, stationName) {
    document.getElementById(inputType).value = stationName;
    
    let dropdownId = inputType === 'source' ? "filteredsourcestation" : "filtereddestinationstation";
    document.getElementById(dropdownId).style.display = "none";
  }

  function filterFunction(type) {
    var input, filter, div, items, i;

    input = document.getElementById(type === 'source' ? "source" : "destination");
    filter = input.value.toUpperCase();

    div = document.getElementById(type === 'source' ? "filteredsourcestation" : "filtereddestinationstation");
    items = div.getElementsByClassName("dropdown-item");

    div.style.display = filter.length > 0 ? "block" : "none";

    let hasVisibleLinks = false;

    for (i = 0; i < items.length; i++) {
      let txtValue = items[i].textContent || items[i].innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        items[i].style.display = "";
        hasVisibleLinks = true;
      } else {
        items[i].style.display = "none";
      }
    }

    div.style.display = hasVisibleLinks ? "block" : "none";
  }
</script>



</html>

app/views/trains/search_result.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Available Trains</title>
  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body {
      background-color: #f2f2f2; /* Light gray background for the body */
      font-family: Arial, sans-serif;
    }
    .heading {
      text-align: center;
      font-weight: bold;
      color: #003b70; /* Dark blue color for headings */
      margin-top: 30px;
      margin-bottom: 20px;
    }
    .train-list {
      padding: 0;
      list-style: none;
      margin: 0;
    }
    .train {
      font-size: 16px;
      padding: 15px;
      margin-bottom: 15px;
      border: 1px solid #003b70; /* Dark blue border */
      border-radius: 5px;
      background-color: #ffffff; /* White background for the train details */
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* Light shadow for depth */
    }
    .train div {
      margin-bottom: 5px; /* Spacing between lines of text */
    }
    .train button {
      margin-top: 10px;
      border-radius: 5px; /* Rounded corners for the button */
    }
    .error {
      text-align: center;
      font-size: 24px;
      color: #d32f2f; /* Red color for error messages */
      margin-top: 20px;
    }
    .btn-primary {
      background-color: #003b70; /* Dark blue button */
      border-color: #003b70;
      color: #ffffff;
    }
    .btn-primary:hover {
      background-color: #002f5d;
      border-color: #002f5d;
    }
    .departure_error{
      color: red;
    }
  </style>
</head>
<body>

  <h1 class="heading">Available Trains</h1>

  <% if @trains.any? %>
    <ul class="train-list">
      <% @trains.each do |train| %>
        <% @s_time = Stop.where(train_id: train.id, station_id: @source_station.id).pick(:departure_time) %>
        <% @d_time = Stop.where(train_id: train.id, station_id: @destination_station.id).pick(:arrival_time) %>
        <%= form_with url: search_result_trains_path, method: :get, local: true do |form| %>
          <%= form.hidden_field :train_id, value: train.id %>
          <%= form.hidden_field :source, value: @source_station.name %>
          <%= form.hidden_field :destination, value: @destination_station.name %>
          <li class="train">
            <% if train_departured?(@s_time)%>
              <div class="departure_error">Train departured</div>
            <% elsif chart_prepared?(@s_time)%>
              <div class="departure_error">can't book tickets anymore chart already prepared!</div>
            <%end%>
            <div><strong><%= train.train_name %></strong></div>
            <div><%= @source_station.name %> to <%= @destination_station.name %></div>
            <div>Starts at: <%= (@s_time.in_time_zone('Asia/Kolkata'))&.strftime('%H:%M') %></div>
            <div>Reaches at: <%= (@d_time.in_time_zone('Asia/Kolkata'))&.strftime('%H:%M') %></div>
            <div>Seats: <%= train.capacity %></div>
            <%= form.submit "Book Ticket", class: "btn btn-primary", disabled: chart_prepared?(@s_time) %>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <p class="error">No trains found</p>
  <% end %>

  <!-- Bootstrap JS Bundle with Popper -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/trains/update.html.erb
<h1>Trains#update</h1>
<p>Find me in app/views/trains/update.html.erb</p>