config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'trains/new'
  # get 'trains/create'
  # get 'trains/show'
  # get 'trains/edit'
  # get 'trains/update'
  # get 'trains/destroy'

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "homes#index"

  resources :homes

  resources :payments
  # get '/search', to: 'trains#search'

  resources :trains do
    # resources :tickets, only: [:show, :create, :destroy]
    collection do
      get 'search'
      get 'search_result'
    end
  end
  resources :tickets

  resources :passengers

  devise_for :users do
    resources :tickets
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    render
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/homes/index.html.erb
<html>
  <head>
    <style>
     body{
      background-color: lightgrey;
     }
     .container{
      text-align:center;
     }
     .mainheading{
      text-align: center;
      font-size:40px;
     }
     marquee{
      font-size:30px;
      margin-top: 30px;
      color: #1d0c91;
     }
    </style>
  </head>
  <body>
      <%if user_signed_in? %>
        <%# <div>Welcome <%=current_user.email %></div> 
        <marquee>Welcome To Railway Booking System </marquee>
      <%else%>
      <div class="container">
        <h1 class="mainheading">Welcome...</h1>
        <h3 class="subheading">click here to sign in</h3>
        <%= link_to "Sign in", new_user_session_path%>
        <%= link_to "Sign in as Admin", new_admin_user_session_path %>
      </div>
      <%end%>
  </body>
</html>