config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'trains/new'
  # get 'trains/create'
  # get 'trains/show'
  # get 'trains/edit'
  # get 'trains/update'
  # get 'trains/destroy'

  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "homes#index"

  resources :homes

  resources :payments
  # get '/search', to: 'trains#search'

  resources :trains do
    # resources :tickets, only: [:show, :create, :destroy]
    collection do
      get 'search'
      get 'search_result'
    end
  end
  resources :tickets

  resources :passengers

  devise_for :users do
    resources :tickets
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railway Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload"%>
    <%= javascript_importmap_tags %>

    <style>
      .navbar{
      background-color: #1e1d1e;
      height: 70px;
      border-radius: 20px;
      }
      .navbar ul{
       overflow: auto;
      }
      .navbar li{
        float: left;
        list-style: none;
        margin: 13px 20px;
        color: white;
      }
      .navbar li a{
        padding: 3px 3px;
        text-decoration: none;
        color: white;
      }
      .navbar li a:hover{
        color: red;
      }
      #username{
        float:right;
      }
    </style>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><%= link_to "Home", homes_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Search page", trains_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "My Tickets", tickets_path, class: "nav-link" %></li>
              <%# <% if user_signed_in? %>
              <li class="nav-item"><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger nav-link" %></li>
              <li class="nav-item ml-auto"><%= "Welcome #{current_user.email}" %></li>
              <%# <% end %>
            </ul>
          </div>
        </nav>
      </header>
    <%end%>
    <%= yield %>
  </body>
</html>